apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secrets
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  user-password: {{ .Values.postgresql.password | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}