apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications-service.fullname" . }}-secrets
  labels:
    {{- include "notifications-service.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc | quote }}